-- CREATE DATABASE `library`;
USE library;

DROP TABLE IF EXISTS `penalty`;
DROP TABLE IF EXISTS `record`;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `card`;
DROP TABLE IF EXISTS `book`;
DROP TABLE IF EXISTS `admin`;
DROP TABLE IF EXISTS `usertype`;

CREATE TABLE `UserType`(
	type_id TINYINT PRIMARY KEY AUTO_INCREMENT,
	type_name VARCHAR(20),
	quota TINYINT
) AUTO_INCREMENT = 1;

CREATE TABLE `Admin`(
	admin_id INT PRIMARY KEY AUTO_INCREMENT,
	account VARCHAR(20) UNIQUE NOT NULL,
	`name` VARCHAR(20),
	`password` VARCHAR(20) NOT NULL
) AUTO_INCREMENT = 1;

CREATE TABLE `Book`(
	book_id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(20) NOT NULL,
	author VARCHAR(20),
	price NUMERIC(5,2),
	quantity INT DEFAULT 1
) AUTO_INCREMENT = 1;

CREATE TABLE `Card`(
	card_id INT PRIMARY KEY AUTO_INCREMENT,
	balance NUMERIC(5,2) DEFAULT 100.0,
	amount TINYINT DEFAULT 0,
	quota TINYINT DEFAULT 5
) AUTO_INCREMENT = 1000000;

CREATE TABLE `User`(
	user_id INT PRIMARY KEY AUTO_INCREMENT,
	account VARCHAR(20) UNIQUE NOT NULL,
	`name` VARCHAR(20),
	`password` VARCHAR(20) NOT NULL,
	card_id INT,
	type_id TINYINT NOT NULL,
	FOREIGN KEY (type_id) REFERENCES UserType(type_id),
	FOREIGN KEY (card_id) REFERENCES Card(card_id)
) AUTO_INCREMENT = 1;

CREATE TABLE `Record`(
	record_id INT PRIMARY KEY AUTO_INCREMENT,
	card_id INT NOT NULL,
	book_id INT NOT NULL,
	borrow_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	return_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (book_id) REFERENCES Book(book_id),
	FOREIGN KEY (card_id) REFERENCES Card(card_id)
) AUTO_INCREMENT 1;

CREATE TABLE `Penalty`(
	penalty_id INT PRIMARY KEY AUTO_INCREMENT,
	card_id INT NOT NULL,
	record_id INT NOT NULL,
	admin_id INT NOT NULL,
	amount NUMERIC(5,2) NOT NULL,
	FOREIGN KEY (card_id) REFERENCES Card(card_id),
	FOREIGN KEY (record_id) REFERENCES Record(record_id),
	FOREIGN KEY (admin_id) REFERENCES `Admin`(admin_id)
) AUTO_INCREMENT 1;


INSERT INTO `card`VALUES(NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `card`VALUES(NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `card`VALUES(NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `card`VALUES(NULL, DEFAULT, DEFAULT, DEFAULT);


-- 类型编号，类型名， 限额
INSERT INTO usertype VALUES(NULL, '学生', 8);
INSERT INTO usertype VALUES(NULL, '教师', 10);


-- user_id，账号， 姓名， 密码， 卡号， 用户类型
INSERT INTO `user` VALUES(NULL, 'asdfas','张三','124ac34', NULL, 1);
INSERT INTO `user` VALUES(NULL, 'fasd1','丽丽','12344', NULL,1);
INSERT INTO `user` VALUES(NULL, 'ga341a','张张','12314', 1000000, 2);
INSERT INTO `user` VALUES(NULL, 'gas14a','李丽','123g4', 1000002, 1);
INSERT INTO `user` VALUES(NULL, 'gas4a','旺旺','122a34',1000003, 2);
INSERT INTO `user` VALUES(NULL, 'gas1a','李志','12ac34',NULL, 1);
INSERT INTO `user` VALUES(NULL, 'gaaa','李倩','12ba34',NULL, 1);
INSERT INTO `user` VALUES(NULL, 'aq1ca','孙子','12c134',NULL, 2);

-- 						书id， 书名， 		作者， 价格， 数量
INSERT INTO book VALUES(NULL, 'Java编程思想',NULL,87.5, 52);
INSERT INTO book VALUES(NULL, 'Java核心内容',NULL,72.5, 52);
INSERT INTO book VALUES(NULL, 'Head First Java','ABC',47.5, 52);
INSERT INTO book VALUES(NULL, 'JVM详解','未知',75.5, DEFAULT);
INSERT INTO book VALUES(NULL, '十万个为什么',NULL,77.5, DEFAULT);

-- 编号， 用户名， 密码
INSERT INTO `Admin` VALUES(NULL, 'admin1','陶怡', 'abcd');
INSERT INTO `Admin` VALUES(NULL, 'admin2','金新', '4321');
INSERT INTO `Admin` VALUES(NULL, 'admin3','赵飞', '1234');


-- 借阅记录 			 记录号 卡号  书号  借时间 还时间
INSERT INTO record VALUES(NULL, 1000000, 4, DEFAULT, DEFAULT);
INSERT INTO record VALUES(NULL, 1000002, 4, DEFAULT, DEFAULT);
INSERT INTO record VALUES(NULL, 1000003, 3, DEFAULT, DEFAULT);
INSERT INTO record VALUES(NULL, 1000000, 4, DEFAULT, DEFAULT);
INSERT INTO record VALUES(NULL, 1000002, 5, DEFAULT, DEFAULT);

-- 罚款记录


